### ISSUE TITLE
Curl works correctly only with OpenSSL as backend

### ISSUE THREAD

**Issue by dimakuv** [cloud-security-research/sgx-ra-tls#1]
SGX-RA-TLS uses Curl to send HTTPS requests to the IAS web service. For HTTPS, Curl needs to use a TLS library. By default, Curl is built against OpenSSL which works nicely.

Curl can be also built with an alternative TLS library, like mbedTLS or WolfSSL.

For clearness, one would want to build Curl with mbedTLS if the attester is built with mbedTLS and thus decouple SGX-RA-TLS from OpenSSL completely. (Same for WolfSSL.)

This is impossible however. mbedTLS and WolfSSL do not support large IAS responses [("We don't support fragmentation of ClientHello")](https://github.com/ARMmbed/mbedtls/blob/b363382ba4c0489b6045112dbaf100758ec72cc2/library/ssl_srv.c#L1378). Thus, Curl built with these libs fails with obscure error (`CURLE_SSL_CONNECT_ERROR (35)`).

**Conclusion:** Curl *must be* built with OpenSSL as backend, because it is the only library that correctly communicates with IAS. Even if our attester is built against mbedTLS/WolfSSL, we cannot reuse their functionality in Curl. Thus, we are stuck with *two TLS libs* as dependencies in SGX-RA-TLS.

**Comment by thomasknauth** [comment]
Instead of waiting for mbedtls and wolfssl to support fragmented handshake patches, we may get away with a simple patch that increases the maximum handshake packet size to accommodate whatever gigantic handshake packets IAS sends.

wolfSSL defines MAX_HANDSHAKE_SZ in internal.h. For now, only having wolfSSL being able to communicate with IAS would be sufficient for my purposes, i.e., I need a version of this which does not use OpenSSL.

We still depend on OpenSSL though for some base64 en-/decoding though. This would need to be changed too.

**Comment by thomasknauth** [comment]
The ECDSA update will resolve this since IAS version 5 no longer uses client certificates for authentication.
