### ISSUE TITLE
Sample HTTPS Server fails to remain launched when run using SGX-LKL

### ISSUE THREAD

**Issue by njriasan** [cloud-security-research/sgx-ra-tls#8]
I am attempting to follow the example for launching the Python-based HTTPS server inside the docker container but the server keeps crashing before I can get any client to connect. The client begins launching with the message

LD_PRELOAD=/ldpreload.so SGXLKL_TAP=sgxlkl_tap0 RATLS_AESMD_IP=10.0.1.254 SGXLKL_HEAP=268435456 SGXLKL_KEY=/project/sgxlkl/sgx-lkl/build/config/enclave_debug.key sgx-lkl/build/sgx-lkl-run sgx-lkl/apps/https-server/sgxlkl-miniroot-fs.img /usr/bin/python /https-server.py
ERROR: ld.so: object '/ldpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Server listening on 10.0.1.1:4443

which appears to be the normal intended behavior. However a couple of seconds later before I have launched any client it errors with the message:

Traceback (most recent call last):
  File "/https-server.py", line 32, in <module>
    httpd.socket = ssl.wrap_socket (httpd.socket, keyfile='/tmp/key.pem', certfile='/tmp/crt.pem', server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 949, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 560, in __init__
    self._context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:2798).

I was able to successfully run the attestation examples for both Graphene (including mutual attestation) and the wolfssl example for SGX-LKL if that is of any use for you. I am also registered with intel and have my key and certificate in the default location.

**Comment by njriasan** [comment]
Upon further analysis I can find that the cert and key are generated by the preload library.

**Comment by shankari** [comment]
@njriasan in general, this error seems to be related to invalid key or cert files
e.g. https://stackoverflow.com/questions/30109449/what-does-sslerror-ssl-pem-lib-ssl-c2532-mean-using-the-python-ssl-libr

Couple of troubleshooting steps from those docs:
- do you have a password in your keyfile?
- do you have the complete cert chain in the certfile? 
> The certfile string must be the path to a single file in PEM format containing the certificate as well as any number of CA certificates needed to establish the certificate’s authenticity.

**Comment by njriasan** [comment]
So this is for the key and cert which is self-signed and generated on a per session basis by the ld-preload library. I have verified that they are in pem format and match. I am not sure how to check if the entire chain is complete but it should be because I believe the certificate is a self signed certificate from Intel Labs.

**Comment by njriasan** [comment]
Ok I figured out the issue. The issue is that the alpine partition used to generate the sgx-lkl image relies on libressl which is rejecting the certification. This project, https://github.com/getdnsapi/stubby/issues/102, seems to indicate this is a known issue, although I'm not sure how much of it is directly related to their own project (I'm not at all familiar with it). To fix this I had the alpine partition install openssl and then rebuild python from source (because the python package for alpine 3.6 relies on libressl). I will submit a pull request with this. A cleaner longterm solution would be to build a new python 2.7.15 package that installs and relies on openssl rather than libressl. I am not familiar with the process of doing this but can try figure it out if people feel this would be helpful. I can't imagine its too hard so long assuming I don't need to update it frequently.

**Comment by shankari** [comment]
@njriasan great debugging! another option would be to base the docker image on the minimal release of ubuntu instead of alpine https://blog.ubuntu.com/2018/07/09/minimal-ubuntu-released Since ubuntu uses openssl by default, the python package from the distribution will Just Work. That should be a lot less of a maintenance hassle long-term.

Maintainers, any thoughts on which direction you would like to to take? (@thomasknauth ?)

**Comment by shankari** [comment]
so it might be as easy as just installing python directly from ubuntu instead of from alpine; e.g. remove the line 
https://github.com/cloud-security-research/sgx-ra-tls/blob/master/sgxlkl/https-server/buildenv.sh#L8

Maintainers, any thoughts on why you are installing the alpine linux python although your base is from ubuntu?

**Comment by cpriebe** [comment]
SGX-LKL requires applications (in this case Python) to be linked against musl libc. Alpine uses musl by default which is why Python is installed from the Alpine repository.

**Comment by cpriebe** [comment]
I am not an author of this repository, so take everything I say with a grain of salt :)

This issue is specifically about SGX-LKL which is an alternative to Graphene and SCONE. If you are using/are planning to use Graphene, this issue should not affect you!

**Comment by shankari** [comment]
ah, thanks for the information.

We want to use graphene with python, but the only example with python that we could find used sgx-lkl. So @njriasan decided to first get the standard SGX-LKL example to work and then to try the same python code with graphene.

But now it looks like it might have been easier to just get python + graphene to work.

Ah well, at least we got to contribute to the project and fix the sgx-lkl example...

**Comment by thomasknauth** [comment]
Thanks @shankari and @njriasan for digging into this. I am sorry that you ran into trouble following the example. Last time I tried, it actually worked. As you observed, these days it fails. I am still unsure what exactly changed. It seems Alpine's python always used LibreSSL as opposed to OpenSSL. I can only guess that LibreSSL recently changed its default policy to reject self-signed certificates? Who knows.

Compiling Python from source against OpenSSL is one way to fix this particular example. I was actually hoping to pin a particular version of the Python/libressl version that the examples works with to get around the manual compilation. Let me mull over this a bit longer.

As a side note: as you discovered, I use Ubuntu to develop and run most of the code. SGX-LKL requires Alpine, since it uses musl as its default C library. Since, SGX-LKL modifies the C library, it's not an option to switch aways from Alpine to Ubuntu to resolve this particular issue.

**Comment by shankari** [comment]
@thomasknauth sounds good. We will probably try graphene + python next.

Would you like us to contribute an example for that so that other prospective python users won't have to do the two-step process like we are?

Say "hi" to Mona for us :)

**Comment by njriasan** [comment]
@thomasknauth from what I found on https://pkgs.alpinelinux.org/packages alpine only has 1 python package available for Alpine 3.6 https://pkgs.alpinelinux.org/package/edge/main/x86/python2 and it seems to depend on default on libressl. If you want to avoid manual compilation it seems feasible to add a package that depends on openssl instead directly to the alpine packages that are publicly available. I haven't done it before but it doesn't seem difficult so I would be willing to.

**Comment by shankari** [comment]
@thomasknauth would you welcome an example of using `HTTPServer` with graphene as well? That was going to be our next step and we could contribute that example if it helps.

**Comment by thomasknauth** [comment]
There is actually a reason I picked SGX-LKL for this particular case: Exposing the key through the filesystem to the application is OK with SGX-LKL, since /tmp lives in enclave memory. If I am correct, Graphene does currently not have the option for an in-enclave-memory file system. Writing the key to /tmp on Graphene would expose the key to the untrusted environment.

If you want to have something similar on Graphene, it would probably be best to write some additional code to make the RA-TLS library directly accessible from Python; as opposed to the indirection through the file system.
